import Foundation

enum StartupScriptInstaller {

    /// What to launch for a session, including any env overrides needed to make
    /// the startup script source after the user's normal init.
    struct Plan: Equatable {
        let executable: String
        let args: [String]
        /// Env vars that the surface launcher MUST set on top of whatever else
        /// it's already passing to the shell.
        let envOverrides: [String: String]
    }

    /// Returns the launch plan for a session.
    ///
    /// When `startupScript` is empty: launch the configured shell as a login
    /// shell (`-l`) with no extra setup.
    ///
    /// Otherwise: write the script to a per-session rc file and ask the shell
    /// to source it after the user's normal init. Mechanism is shell-specific:
    ///
    /// - **zsh**: write `<dir>/.zshrc` (which sources `~/.zshrc` first then the
    ///   user's snippet) and set `ZDOTDIR=<dir>` so zsh picks it up. zsh does
    ///   NOT accept bash's `--rcfile`, so the previous bash-style flag would
    ///   silently fail.
    /// - **bash**: pass `--rcfile <file> -i` (still sources `~/.bashrc` first
    ///   inside the file).
    /// - **other shells**: log a warning and ignore the startup script. We don't
    ///   know how to inject one in fish/nu/etc. without per-shell heuristics.
    static func plan(
        shell: String,
        startupScript: String,
        sessionId: String
    ) throws -> Plan {
        let trimmed = startupScript.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty else {
            return Plan(executable: shell, args: ["-l"], envOverrides: [:])
        }

        let basename = (shell as NSString).lastPathComponent

        switch basename {
        case "zsh":
            // ZDOTDIR-scoped .zshrc that sources the user's real ~/.zshrc then
            // appends the user-supplied snippet. zsh always picks `.zshrc` from
            // ZDOTDIR if set; the file MUST be named `.zshrc`.
            let dir = Paths.appSupportRoot
                .appendingPathComponent("rcfiles", isDirectory: true)
                .appendingPathComponent(sessionId, isDirectory: true)
            try Paths.ensureDirectoryExists(dir)
            let rcfile = dir.appendingPathComponent(".zshrc")
            let body = """
            # Generated by Alas — sources user init then session script.
            [ -f "$HOME/.zshrc" ] && source "$HOME/.zshrc"
            \(trimmed)
            """
            try body.write(to: rcfile, atomically: true, encoding: .utf8)
            return Plan(
                executable: shell,
                args: ["-i"],
                envOverrides: ["ZDOTDIR": dir.path]
            )

        case "bash":
            let dir = Paths.appSupportRoot
                .appendingPathComponent("rcfiles", isDirectory: true)
            try Paths.ensureDirectoryExists(dir)
            let rcfile = dir.appendingPathComponent("\(sessionId).bashrc")
            let body = """
            # Generated by Alas — sources user init then session script.
            [ -f "$HOME/.bashrc" ] && source "$HOME/.bashrc"
            \(trimmed)
            """
            try body.write(to: rcfile, atomically: true, encoding: .utf8)
            return Plan(
                executable: shell,
                args: ["--rcfile", rcfile.path, "-i"],
                envOverrides: [:]
            )

        default:
            // Fish, nushell, etc. — startup script silently dropped. Add per-shell
            // handling here if/when we want to support them.
            return Plan(executable: shell, args: ["-l"], envOverrides: [:])
        }
    }
}
