import Foundation

enum StartupScriptInstaller {
    /// Returns shell argv to use for the session, sourcing the startup script after user init.
    /// Strategy: pre-source a wrapper rcfile that first sources ~/.zshrc, then the user script.
    static func shellArgv(
        shell: String,
        startupScript: String,
        sessionId: String
    ) throws -> (executable: String, args: [String]) {
        let trimmed = startupScript.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty else {
            return (shell, ["-l"])
        }
        let dir = Paths.appSupportRoot.appendingPathComponent("rcfiles", isDirectory: true)
        try Paths.ensureDirectoryExists(dir)
        let url = dir.appendingPathComponent("\(sessionId).zshrc")
        let body = """
        # Generated by Alas — sources user init then session script
        [ -f "$HOME/.zshrc" ] && source "$HOME/.zshrc"
        \(trimmed)
        """
        try body.write(to: url, atomically: true, encoding: .utf8)
        return (shell, ["--rcfile", url.path, "-i"])
    }
}
