import SwiftUI

typealias ReviewChangesRail = DiffReviewRail
typealias ReviewChangesRailRow = DiffReviewRailRow
typealias ReviewChangesRailRows = DiffReviewRailRows
typealias ReviewChangesAccessibilityMarker = DiffReviewAccessibilityMarker
