import CoreGraphics

typealias ReviewChangesSectionFrame = DiffReviewSectionFrame
typealias ReviewChangesScrollSpy = DiffReviewScrollSpy
typealias ReviewChangesActiveFileSelection = DiffReviewActiveFileSelection
typealias ReviewChangesProgrammaticScrollController = DiffReviewProgrammaticScrollController
